### ISSUE TITLE
LazyLoad property and BeginEdit

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2444]
### Discussed in https://github.com/MarimerLLC/csla/discussions/2395

<div type='discussions-op-text'>

<sup>Originally posted by **amselem** July 30, 2021</sup>
Hi,
I have a bo with some lazyload properties shown in a windows form app. 
Since the lazyload properties are heavy to load , I only load them if the user clicks on their respective tabpage. The user can click in the tabpage before or after beginning an edit in this form.
When the user begins the form edit I call my bo.BeginEdit()  so I can call bo.CancelEdit() if the user wants to rollback his changes.
However the Lazyload fields are rolled back only if they were loaded previously (i.e. if the user clicked in the tabpage). If the user begins an edit, then clicks on the tabpage, the lazyload property is not rolled back on an undo operation.  

What's the best/correct approach to solve this inconsistent behavior?

Kind regards

</div>

It seems that there are possible scenarios here.

1. In an undo the previous value was null - which your suggested change addresses by retaining the new value - _except_ I can imagine a scenario where it really _was_ null and should return to null - maybe your change needs to only happen if the property is marked for LazyLoad?
2. In an undo the previous value was _a different instance_ - so we should revert to that previous instance? That's maybe unrealistic, since it will always _technically_ be a different instance due to deserialization. Hmm...
3. In an undo the previous value was an instance and the _new value_ is null - so we should revert to that previous instance

This backlog issue is to **fix scenario number 1**.

**Comment by rockfordlhotka** [comment]
@amselem can you test the v5.5.1 preview I pushed to NuGet to see if it resolves your issue?

**Comment by amselem** [comment]
@rockfordlhotka it's still failing, but I think there maybe something wrong with the preview because when I'm debugging the issue and Visual Studio fetchs the code from github , it looks like the same unchanged code.

Indeed I see the old code when looking at: 
https://github.com/MarimerLLC/csla/blob/v5.x/Source/Csla.Shared/Core/FieldManager/FieldDataManager.cs
https://github.com/MarimerLLC/csla/blob/main/Source/Csla/Core/FieldManager/FieldDataManager.cs

I see the new code at:
https://github.com/rockfordlhotka/csla/blob/v5.5.1-pre/Source/Csla.Shared/Core/FieldManager/FieldDataManager.cs

Maybe the fix didn't get into the preview?  It looks like there's a pull request but I don't know if you have to approve first (I'm fairly new to the github workflow)

**Comment by rockfordlhotka** [comment]
Oh, my bad! The PR remains outstanding, maybe you can test the changes in your code base?

**Comment by amselem** [comment]
I tested the changes and now the LazyLoad undo works as expected  :)
