### ISSUE TITLE
Enhance GraphMerger to support BusinessBindingListBase type

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#2901]
I have added a `PersonItems : BusinessBindingListBase<PersonItems, PersonItem>` to `PersonEdit`. After the `Save` completes successfully I am getting the following error:

![image](https://user-images.githubusercontent.com/21806535/163755175-f5a80ff3-ec53-495c-91cf-a63837bf388a.png)

This sample demonstrates the problem:
[BlazorExample-InvalidGenericArguments.zip](https://github.com/MarimerLLC/csla/files/8503493/BlazorExample-InvalidGenericArguments.zip)

It doesn't seem to matter if the `PersonItems` property is lazy-loaded or not, so it's probably not related to ["Property get not allowed" with LazyGetProperty](https://github.com/MarimerLLC/csla/issues/2870).

**Comment by rockfordlhotka** [comment]
This is an aside @michaelcsikos, but `BusinessBindingListBase` exists purely for Windows Forms. `BusinesListBase` exists to support all other platforms (including Blazor). Only Windows Forms requires the old behaviors implemented by `BusinessBindingListBase`.

**Comment by rockfordlhotka** [comment]
@michaelcsikos have you tested this against the current code in the `main` branch where I fixed the other lazy property issue? I ask, because I'm unable to replicate this issue against the current codebase.

**Comment by michaelcsikos** [comment]
@rockfordlhotka I can confirm that this error only appears when using `BusinessBindingListBase`, and it still happens in `6.0.0-R22042501`. If a business library is to be used in Blazor and Windows Forms, we need to use `BusinessBindingListBase`, right?

**Comment by rockfordlhotka** [comment]
Yes, that's sadly true.

So my test has

```c#
  [Serializable]
  public class PersonList : BusinessBindingListBase<PersonList, PersonEdit>
  {
  }
```

And in `PersonEdit`

```c#
    public static readonly PropertyInfo<PersonList> ChildListProperty = 
      RegisterProperty<PersonList>(nameof(ChildList), RelationshipTypes.LazyLoad);
    public PersonList ChildList
    {
      get => LazyGetProperty(ChildListProperty, () =>
        ApplicationContext.GetRequiredService<IDataPortal<PersonList>>().Create());
      set => SetProperty(ChildListProperty, value);
    }
```

So the same thing you have in the Blazor test right?

I'm able to create, save, edit, save the root `PersonEdit` without error in my tests.

So maybe the issue is actually in the Blazor UI code? Because it isn't in the data portal or graph merger, as my tests use local and remote data portal, and graph merger.

**Comment by rockfordlhotka** [comment]
@michaelcsikos I am unable to replicate the issue in Blazor when using today's prerelease, or in my other tests.

**Comment by michaelcsikos** [comment]
@rockfordlhotka If you touch the `ChildList` in `PersonEdit.Create()` can you reproduce the error?

```cs
[Create]
private void Create()
{
  Id = -1;
  _  = ChildList; // Invalid generic arguments

  BusinessRules.CheckRules();
}
```

**Comment by michaelcsikos** [comment]
```cs
[Serializable]
public class ChildList : BusinessBindingListBase<ChildList, PersonEdit>
{
  [Create]
  private void Create()
  {
  }
}

public static readonly PropertyInfo<ChildList> ChildListProperty
                 = RegisterProperty<ChildList>(nameof(ChildList), RelationshipTypes.LazyLoad);
public ChildList ChildList
{
  get => LazyGetProperty(ChildListProperty, () =>
    ApplicationContext.GetRequiredService<IDataPortal<ChildList>>().Create());
  private set => SetProperty(ChildListProperty, value);
}

[Create]
private void Create()
{
  Id = -1;
  _  = ChildList;

  BusinessRules.CheckRules();
}
```

**Comment by rockfordlhotka** [comment]
@michaelcsikos thank you, that was the missing link. As before, the issue was in GraphMerger - though in this case it was because there was never support for the old BindingList type.
